/**
 * Export utilities for ASCII art
 */

/**
 * Export ASCII text as .txt file
 * @param {string} text - ASCII text
 * @param {string} filename - Output filename
 */
export function exportTXT(text, filename = 'ascii_isw.txt') {
  const footer = '\n\ngenerated by ASCII Converter - ironsignalworks.com\n';
  const blob = new Blob([text + footer], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  
  URL.revokeObjectURL(url);
}

/**
 * Export ASCII text as PNG image
 * @param {string} text - ASCII text
 * @param {HTMLElement} referenceElement - Element to get font styles from
 * @param {string} inkColor - Text color
 * @param {number} scale - Scale factor
 * @param {string} filename - Output filename
 */
export function exportPNG(text, referenceElement, inkColor, scale = 1, filename = 'ascii_isw.png') {
  const computedStyle = getComputedStyle(referenceElement);
  const outFont = parseFloat(computedStyle.fontSize) || 8;
  const outLine = parseFloat(computedStyle.lineHeight) || 8;
  const ratio = outLine / outFont;
  
  const baseFont = outFont * scale;
  const baseLine = baseFont * ratio;
  const pad = Math.max(6, Math.round(8 * scale));
  
  const lines = text.split("\n");
  
  // Measure text width
  const measureCanvas = document.createElement('canvas');
  const measureCtx = measureCanvas.getContext('2d');
  if (!measureCtx) {
    console.error('Failed to get canvas context');
    return;
  }
  
  measureCtx.font = `${baseFont}px monospace`;
  const maxLineWidth = Math.max(...lines.map(l => measureCtx.measureText(l).width));
  const width = Math.min(6000, maxLineWidth + pad * 2);
  const textHeight = Math.min(6000, Math.ceil(lines.length * baseLine + pad * 2));
  
  // Calculate footer height
  const clamp = (v, min, max) => Math.max(min, Math.min(max, v));
  const footerH = clamp(
    Math.round(textHeight * 0.08),
    Math.round(16 * scale),
    Math.round(72 * scale)
  );
  const height = textHeight + footerH;
  
  // Create main canvas
  const canvas = document.createElement('canvas');
  canvas.width = Math.ceil(width);
  canvas.height = Math.ceil(height);
  const ctx = canvas.getContext('2d');
  
  if (!ctx) {
    console.error('Failed to get canvas context');
    return;
  }
  
  // Background
  ctx.fillStyle = '#0a0a0a';
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  
  // Border around text area
  ctx.strokeStyle = '#3a3a3a';
  ctx.strokeRect(0.5, 0.5, canvas.width - 1, canvas.height - footerH - 0.5);
  
  // Draw ASCII text
  ctx.font = `${baseFont}px monospace`;
  ctx.textBaseline = 'top';
  ctx.fillStyle = inkColor || '#d0d0d0';
  
  for (let i = 0; i < lines.length; i++) {
    ctx.fillText(lines[i], pad, Math.round(pad + i * baseLine));
  }
  
  // Footer background
  ctx.fillStyle = '#000';
  ctx.fillRect(0, canvas.height - footerH, canvas.width, footerH);
  
  // Footer text
  let footerFont = clamp(
    Math.floor(footerH * 0.6),
    Math.floor(10 * scale),
    Math.floor(28 * scale)
  );
  
  ctx.fillStyle = '#bdbdbd';
  ctx.textBaseline = 'alphabetic';
  ctx.font = `${footerFont}px monospace`;
  
  const signature = 'generated by ASCII Converter - ironsignalworks.com';
  let sigWidth = ctx.measureText(signature).width;
  const innerW = canvas.width - pad * 2;
  
  // Shrink font if needed to fit signature
  while (sigWidth > innerW && footerFont > 8) {
    footerFont -= 1;
    ctx.font = `${footerFont}px monospace`;
    sigWidth = ctx.measureText(signature).width;
  }
  
  const sigY = canvas.height - Math.round((footerH - footerFont) / 2) - Math.floor(footerFont * 0.2);
  ctx.fillText(signature, pad, sigY);
  
  // Export
  const dataURL = canvas.toDataURL('image/png');
  const anchor = document.createElement('a');
  anchor.href = dataURL;
  anchor.download = filename;
  anchor.click();
}
